"""auto-comments5

Revision ID: 78a7015a27dc
Revises: eb3bdeada8da
Create Date: 2021-12-25 04:29:13.360871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a7015a27dc'
down_revision = 'eb3bdeada8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
