"""auto-comments6

Revision ID: 9fe757cf1443
Revises: 78a7015a27dc
Create Date: 2021-12-25 04:33:10.578498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe757cf1443'
down_revision = '78a7015a27dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
